services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: postgres_aa
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=challenge'
      - 'POSTGRES_PASSWORD=challenge'
      - 'POSTGRES_USER=challenge'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U challenge -d challenge"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: